pipeline {
    agent {
        dockerfile {
            dir 'automation'
            reuseNode true
        }
    }


    stages {
        stage('Clippy') {
            steps {
                sh 'cargo clippy'
            }
        }
        stage('Rustfmt') {
            steps {
                sh 'cargo fmt'
            }
        }
        stage('Docs') {
            steps {
                sh 'cargo +nightly doc'
            }
        }
        stage('Check') {
            steps {
                sh 'cargo check --target thumbv6m-none-eabi'
            }
        }
        stage('Check Examples') {
            steps {
                sh 'cargo check --target thumbv6m-none-eabi --examples'
            }
        }
    }
}